{% set name = "jgo" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31824d329dc5824954cc150a9d934c543a227818dc1c0ea6ea20741c2e462b24

build:
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.2
  run:
    - python >=3.8
    - psutil

test:
  requires:
    - openjdk
    - maven
    - python {{ python_min }}
  imports:
    - jgo
  commands:
    - test "${JGO_CACHE_DIR}" = "${CONDA_PREFIX}/jgo"  # [unix]
    - if not "%JGO_CACHE_DIR%" == "%CONDA_PREFIX%\jgo" exit 1  # [win]

about:
  home: https://github.com/scijava/jgo
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Launch Java code from the CLI, installation-free.
  doc_url: https://github.com/scijava/jgo
  dev_url: https://github.com/scijava/jgo

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
