{% set name = "jgo" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d40bd0869e9fb303d06ac59b601a50361c7329b3ee27ccc8fc1c90c0b130023f

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - psutil

test:
  requires:
    - openjdk
    - maven
  imports:
    - jgo
  commands:
    - test "${JGO_CACHE_DIR}" = "${CONDA_PREFIX}/jgo"  # [unix]
    - if not "%JGO_CACHE_DIR%" == "%CONDA_PREFIX%\jgo" exit 1  # [win]

about:
  home: https://github.com/scijava/jgo
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Launch Java code from the CLI, installation-free.
  doc_url: https://github.com/scijava/jgo
  dev_url: https://github.com/scijava/jgo

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
