{% set name = "jgo" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac4e97b740da4e739db118355b8e4f53df2a3ab9f94350dc1c2e7c7e4fda544d

build:
  number: 0
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - openjdk
    - maven
  imports:
    - jgo
  commands:
    - test "${JGO_CACHE_DIR}" = "${CONDA_PREFIX}/jgo"  # [unix]
    - if not "%JGO_CACHE_DIR%" == "%CONDA_PREFIX%\jgo" exit 1  # [win]

about:
  home: https://github.com/scijava/jgo
  license: PUBLIC-DOMAIN
  license_family: PUBLIC-DOMAIN
  summary: 'Launch Java code from the CLI, installation-free.'
  doc_url: https://github.com/scijava/jgo
  dev_url: https://github.com/scijava/jgo

extra:
  recipe-maintainers:
    - ctrueden
    - hanslovsky
    - hadim
