{% set name = "jgo" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7631d1c25f1b66806e850e6155ea678845762012a13591d662eee8d2d88343b8

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - psutil

test:
  requires:
    - openjdk
    - maven
  imports:
    - jgo
  commands:
    - test "${JGO_CACHE_DIR}" = "${CONDA_PREFIX}/jgo"  # [unix]
    - if not "%JGO_CACHE_DIR%" == "%CONDA_PREFIX%\jgo" exit 1  # [win]

about:
  home: https://github.com/scijava/jgo
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Launch Java code from the CLI, installation-free.
  doc_url: https://github.com/scijava/jgo
  dev_url: https://github.com/scijava/jgo

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
    - hanslovsky
