{% set name = "jgo" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0d40cfd0a2dfaa087f724222cc7d0526e6d5ef7e65f0be0ecaf796e92e0f420

build:
  number: 0
  noarch: python
  entry_points:
    - jgo = jgo.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77.0.0
  run:
    - python >={{ python_min }}
    - cjdk >=0.4.0
    - psutil
    - requests
    - rich >=14.2.0
    - rich-click >=1.9.5
    - semver >=3.0.0
    - tomli >=2.0.0
    - tomli-w >=1.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - jgo
  commands:
    - test "${JGO_CACHE_DIR}" = "${CONDA_PREFIX}/jgo"  # [unix]
    - if not "%JGO_CACHE_DIR%" == "%CONDA_PREFIX%\jgo" exit 1  # [win]

about:
  home: https://github.com/apposed/jgo
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  summary: Launch Java code from Python and the CLI, installation-free.
  doc_url: https://jgo.apposed.org/
  dev_url: https://github.com/apposed/jgo

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
