{% set name = "jgo" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 440d23946d5d91b9855b8329373a7b2b66d77231486cbb82542aed7177122a40

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . -vvv"
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - jgo

about:
  home: https://github.com/scijava/jgo
  license: PUBLIC-DOMAIN
  license_family: PUBLIC-DOMAIN
  summary: 'Launch Java code from the CLI, installation-free. '
  doc_url: https://github.com/scijava/jgo
  dev_url: https://github.com/scijava/jgo

extra:
  recipe-maintainers:
    - ctrueden
    - hanslovsky
    - hadim
