appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YUd8CK3D6s9EhSrYVoikN9dZ9ou1jOneLW/HnkIRkHtxdTe4bbGNtvXCCqM9XRYiw2hGrlnDAOicjb6X+W6yAlNoBmJysNvnNH93DVk91Gc6m53JoAD1fdUnqcDE9uH1Vzh9unqlxkiH1nBUKPgXz8OchKATqj2X2CDDpO0HAOKiRogmrASXa7Y+oz4IgkQlX0FYs0l5Tfhua/H2ai3y9K1UNJCBjLX3TkediN9awN4D18ZSBCWOKGrmLGBoImR3vGnFTCR738dvxHkkk2RN3bdI9PTZhM1XzlBd8pJzqQ3euEirGdAX8SgF5Th3bYVWVXC5dliiR5duGGfZVJrsIHRNLZjLqpPtjXbiUFHwKwYmSpY1awiCYfMV4dh5P6qa/mUBxPIKISgKM8BtFCk7Mtfq5qX1AnCk0cb7VNUKsP+UtZaKkvr8QndAOdAgQ2n7/ZS320IS11/b9L8BlGaIaWOyovbSeP4iHqCrwNcB/6Dipxj03HbzdvoK7KnbHiikPLPm9Ru3F5ViCdFAljOm4LNvaCsA5w63A2XpfDGrwUj9I5+NLRf2aJruj2kvkpoYRIL1bIPUvP+MnB3JnP9qPIjtNaiDatRDJTEucBUYhggwRHkKaIO6NhSd/h54Q611YMlFxYnG1dQNTR6ng1DBOabWv/Cp1XzYgjaQZRPhLs8=}
